name: Remove Roboshop Infra
on: [workflow_dispatch]
jobs:
  DEV-DESTROY:
    runs-on: self-hosted
    #    environment: dev
    #needs: DEV-PLAN
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Init
        run: terraform init -backend-config=env-dev/state.tfvars
      - name: Terraform Destroy
        run: terraform destroy -var-file=env-dev/main.tfvars -auto-approve -var vault_token=${{ secrets.VAULT_TOKEN }}


#  PROD:
#    runs-on: self-hosted
#    needs: UAT
#    steps:
#      - uses: actions/checkout@v4
#      - name: Terraform Init
#        run: terraform init -backend-config=env-prod/state.tfvars -var vault_token=${{ secrets.VAULT_TOKEN }}