name: Provision Roboshop Infra
on: [workflow_dispatch]
jobs:
#  DEV:
#    runs-on: self-hosted
#    steps:
#      - uses: actions/checkout@v4
#      - name: Terraform Init
#        run: terraform init -backend-config=env-dev/state.tfvars
#   DEV-PLAN:
#     runs-on: self-hosted
#     steps:
#       - uses: actions/checkout@v4
#       - name: Terraform Init
#         run: terraform init -backend-config=env-dev/state.tfvars
#       - name: Terraform Plan
#         run: terraform plan -var-file=env-dev/main.tfvars

   DEV-APPLY:
    runs-on: self-hosted
#    environment: dev
    #needs: DEV-PLAN
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Init
        run: terraform init -backend-config=env-dev/state.tfvars
      - name: Terraform Apply
        run: terraform apply -var-file=env-dev/main.tfvars -auto-approve

#  QA:
#    runs-on: ubuntu-latest
      #environment: qa
#    needs: DEV
#    steps:
#      - name: Dummy QA Job
#        run: echo Just a Dummy job
#
#  UAT:
#    runs-on: ubuntu-latest
#    needs: QA
#    environment: uat
#    steps:
#      - name: Dummy UAT Job
#        run: echo Just a Dummy job
#
#  PROD:
#    runs-on: self-hosted
#    needs: UAT
#    steps:
#      - uses: actions/checkout@v4
#      - name: Terraform Init
#        run: terraform init -backend-config=env-prod/state.tfvars